# Custom Language File for Launcher Customizer

[ejs.app]
title = "ByeolAn"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/ByeolYeon"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaSoopURL = "#"
mediaChzzkURL = "https://chzzk.naver.com/c57ab4efaf2548f27214834daeb5c901"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/ByeolYeon"
supportLink = "https://github.com/CustomLauncherLab/ByeolYeon/issues"

[ejs.welcome]
welcomeHeader = "ByeolAn"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."